spring:
  application:
    name: demo-a
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          group: groupA
          version: 1.0
          region: dev
          tag:
          weight: 20
  main:
    allow-bean-definition-overriding: true

springleaf:
  smart:
    discovery:
      group:
        isolation:
          enabled: true
#        key: group




server:
  port: 18080
#  servlet:
#    context-path: /demoa
  tomcat:
    max-threads: 200           #最大并发数，最佳线程数目 = （（线程等待时间+线程CPU时间）/线程CPU时间 ）* CPU数目，1、CPU密集型：操作内存处理的业务，一般线程数设置为：CPU核数 + 1 或者 CPU核数*2。核数为4的话，一般设置 5 或 8 。 2、IO密集型：文件操作，网络操作，数据库操作，一般线程设置为：cpu核数 / (1-0.9)，核数为4的话，一般设置 40
    max-connections: 10000   #接受和处理的最大连接数
    acceptCount: 700         #可以放到处理队列中的请求数

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 30000 #单位毫秒
  ConnectTimeout: 30000 #单位毫秒


#logging:
#  level:
#    com:
#      springleaf: debug
