spring:
  application:
    name: demo-b
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          group: groupB
          version: 2.0
          region: dev
          tag: tagA
          weight: 80
  main:
    allow-bean-definition-overriding: true
server:
  port: 28082

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 30000 #单位毫秒
  ConnectTimeout: 30000 #单位毫秒
