spring:
  application:
    name: demo-a
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          group: groupA
          version: 1.0
          region: dev
          tag:
          weight: 20
  main:
    allow-bean-definition-overriding: true

springleaf:
  smart:
    discovery:
      register:
        config:
          file:
            file: classpath:discovery-rule-register.json


server:
  port: 18080
#  servlet:
#    context-path: /demoa

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 30000 #单位毫秒
  ConnectTimeout: 30000 #单位毫秒


logging:
  level:
    com:
      springleaf: debug
