
spring:
  application:
    name: demo-a
  main:
    allow-bean-definition-overriding: true

  cloud:
    consul:
      host: localhost
      post: 8500
      discovery:
        preferIpAddress: true
        tags: group=groupA,version=1.0,region=dev,weight=20

springleaf:
  smart:
    discovery:
      enabled: true
      group:
        isolation:
          enabled: true
        key: group

      config:
        file:
          file: classpath:discovery-rule.json
#        env:
#          value: '[{"serviceId": "demo-a","conditions": "host=* & application =^[0-9a-zA-Z-]*$","priority":1},{"conditions": "host!=10.0.* & application =^[0-9a-zA-Z-]*$"}]'
#        nacos:
#          server-addr: localhost:8848
#          dataId: discovery-all
#          groupId: DEFAULT_GROUP
#       apollo:
#        namespaceName: application
#        ruleKey: discovery



server:
  port: 18080
#  servlet:
#    context-path: /demoa

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 30000 #单位毫秒
  ConnectTimeout: 30000 #单位毫秒


logging:
  level:
    com:
      springleaf: debug
