

spring:
  application:
    name: demo-b
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      host: localhost
      post: 8500
      discovery:
        preferIpAddress: true
        tags: group=groupA,version=2.0,region=dev,weight=80

server:
  port: 28082

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 30000 #单位毫秒
  ConnectTimeout: 30000 #单位毫秒
