eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      group: groupA
      version: 1.0
      region: dev
      tag:
      weight: 20
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: demo-b
  main:
    allow-bean-definition-overriding: true
server:
  port: 28080

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 30000 #单位毫秒
  ConnectTimeout: 30000 #单位毫秒
